### ISSUE TITLE
Is this repo serious? Maybe we should refactor in rust instead rewritten.

### ISSUE THREAD

**Issue by westhide** [hyprland-rs/hyprland-rs#1]
### Hyprland Version

<details> <summary>System/Version info</summary>

```sh
<Paste the output of the command here>
```

</details>

### Bug or Regression?

Bug

### Description

This repo ***.rs** file not real rust code.

### How to reproduce

This repo can not run like a pure rust repo for now.

**Comment by gnull** [comment]
Looks like a joke. The "rewrite" was done in just one commit and just renamed cpp → rs.

Would be interesting to know the backstory and the view of Hyprland devs on Rust. This seems like a reference to some specific viewpoint.

**Comment by gptlang** [comment]
Was a joke spawned out of the discord server. Vaxry doesn't like Rust.
